#!/usr/bin/env bash

set -e

# Dotbot vars
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
P="${BASEDIR}/plugins"

# Clone submodules
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

# Install packages
PACKAGE_CONFIG="packages-brew.conf.yaml"
sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${PACKAGE_CONFIG}" \
  -p "${P}/dotbot-apt/apt.py" \
  -p "${P}/dotbot-brew/brew.py" \
  -p "${P}/dotbot-snap/snap.py" \
  "${@}"


# Setup user env
ENV_CONFIG="install-macos.conf.yaml"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${ENV_CONFIG}" \
  -p "${P}/dotbot-apt/apt.py" \
  -p "${P}/dotbot-brew/brew.py" \
  -p "${P}/dotbot-snap/snap.py" \
  "${@}"
