#!/usr/bin/env bash

if ! command -v zsh &> /dev/null
then
    echo "zsh could not be found, install it first"
    exit 1
fi


set -e

# Dotbot vars
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Clone submodules
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

# Remove existing zshrc if it's there
rm ~/.zshrc || true

# Setup user env
ENV_CONFIG="install.conf.yaml"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${ENV_CONFIG}" \
  "${@}"

echo "Recommend installing the following packages: fzf, autojump"
