#!/usr/bin/env bash

PLATFORM=$(uname)

if [[ "${PLATFORM}" == "Darwin" ]] && ! command -v brew &> /dev/null; then
  echo "install homebrew with the following /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
  exit 1
fi

if ! command -v zsh &> /dev/null; then
  echo "zsh could not be found, install it first"
  exit 1
fi


set -e

# Dotbot vars
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Clone submodules
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

# Remove existing zshrc if it's there
rm ~/.zshrc || true

# Setup user env
ENV_CONFIG="install.conf.yaml"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${ENV_CONFIG}" \
  "${@}"

echo "Recommend running the following commands:"
echo "scripts/wezterm.sh"
if [[ "${PLATFORM}" == "Darwin" ]]; then
  echo "brew install antigen autojump fd fzf 1password-cli wezterm"
  echo "brew install --cask font-meslo-lg-nerd-font"
fi

if [[ ! "${PLATFORM}" == "Darwin" ]]; then
  echo "Recommend installing the following packages: fzf, autojump, wezterm"
fi